<?php

use App\Models\ChartReading;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        $readings = [
            [
                'source_key' => 'green-g001-1196-212',
                'provisional_name' => 'عمر [اللقب غير محسوم]',
                'normalized_name' => null,
                'node_type' => 'branch_label',
                'reading_status' => 'unclear',
                'confidence' => 48,
                'source_locator' => 'الفرع الأخضر - G001 - الإحداثي 1196,212',
                'notes' => 'اسم عمر ظاهر، أما بقية العبارة أو اللقب فتحتاج الرجوع إلى الصورة الأصلية عالية الدقة.',
            ],
            [
                'source_key' => 'green-g002-1560-215',
                'provisional_name' => 'عبد الرحمن باعبود',
                'normalized_name' => 'عبد الرحمن باعبود',
                'node_type' => 'branch_label',
                'reading_status' => 'readable',
                'confidence' => 94,
                'source_locator' => 'الفرع الأخضر - G002 - الإحداثي 1560,215',
                'notes' => 'الاسم واللقب مقروءان بوضوح جيد.',
            ],
            [
                'source_key' => 'green-g003-969-254',
                'provisional_name' => 'الهاروني جد بيت آل الهاروني',
                'normalized_name' => 'الهاروني جد بيت آل الهاروني',
                'node_type' => 'branch_label',
                'reading_status' => 'readable',
                'confidence' => 93,
                'source_locator' => 'الفرع الأخضر - G003 - الإحداثي 969,254',
                'notes' => 'عنوان فرع ظاهر على ورقة كبيرة.',
            ],
            [
                'source_key' => 'green-g004-741-317',
                'provisional_name' => 'يحيى جد آل بن يحيى',
                'normalized_name' => 'يحيى جد آل بن يحيى',
                'node_type' => 'branch_label',
                'reading_status' => 'readable',
                'confidence' => 94,
                'source_locator' => 'الفرع الأخضر - G004 - الإحداثي 741,317',
                'notes' => 'العبارة مقروءة بوضوح.',
            ],
            [
                'source_key' => 'green-g005-1497-374',
                'provisional_name' => 'عبد الرحمن',
                'normalized_name' => 'عبد الرحمن',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G005 - الإحداثي 1497,374',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g006-1149-364',
                'provisional_name' => 'محمد',
                'normalized_name' => 'محمد',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G006 - الإحداثي 1149,364',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g007-1363-398',
                'provisional_name' => 'حسن',
                'normalized_name' => 'حسن',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G007 - الإحداثي 1363,398',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g008-1713-385',
                'provisional_name' => 'أبو بكر [اللقب غير محسوم]',
                'normalized_name' => null,
                'node_type' => 'person',
                'reading_status' => 'unclear',
                'confidence' => 56,
                'source_locator' => 'الفرع الأخضر - G008 - الإحداثي 1713,385',
                'notes' => 'أبو بكر واضح، والكلمة الثالثة غير محسومة حرفيًا.',
            ],
            [
                'source_key' => 'green-g009-1639-395',
                'provisional_name' => 'عمر [اللقب غير محسوم]',
                'normalized_name' => null,
                'node_type' => 'person',
                'reading_status' => 'unclear',
                'confidence' => 54,
                'source_locator' => 'الفرع الأخضر - G009 - الإحداثي 1639,395',
                'notes' => 'اسم عمر واضح، واللقب يحتاج مراجعة مكبرة.',
            ],
            [
                'source_key' => 'green-g010-1226-414',
                'provisional_name' => 'محمد',
                'normalized_name' => 'محمد',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G010 - الإحداثي 1226,414',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g011-1021-436',
                'provisional_name' => 'الهادي',
                'normalized_name' => 'الهادي',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 96,
                'source_locator' => 'الفرع الأخضر - G011 - الإحداثي 1021,436',
                'notes' => 'توجد علامة صغيرة بعد الاسم قد تكون جزءًا من الخط وليست كلمة مستقلة.',
            ],
            [
                'source_key' => 'green-g012-934-434',
                'provisional_name' => 'حسن الأحمر',
                'normalized_name' => null,
                'node_type' => 'person',
                'reading_status' => 'review',
                'confidence' => 84,
                'source_locator' => 'الفرع الأخضر - G012 - الإحداثي 934,434',
                'notes' => 'حسن واضح، وقراءة الأحمر مرجحة وتحتاج مطابقة حرفية.',
            ],
            [
                'source_key' => 'green-g013-1470-443',
                'provisional_name' => 'شيخ',
                'normalized_name' => 'شيخ',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 97,
                'source_locator' => 'الفرع الأخضر - G013 - الإحداثي 1470,443',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g014-1318-453',
                'provisional_name' => 'سالم',
                'normalized_name' => 'سالم',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G014 - الإحداثي 1318,453',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g015-541-436',
                'provisional_name' => 'عبد الرحمن بن علي خضير',
                'normalized_name' => null,
                'node_type' => 'branch_label',
                'reading_status' => 'review',
                'confidence' => 84,
                'source_locator' => 'الفرع الأخضر - G015 - الإحداثي 541,436',
                'notes' => 'عبد الرحمن بن علي واضح، وضبط خضير يحتاج مراجعة حرفية.',
            ],
            [
                'source_key' => 'green-g016-784-497',
                'provisional_name' => 'سهل جد آل سميط',
                'normalized_name' => null,
                'node_type' => 'branch_label',
                'reading_status' => 'review',
                'confidence' => 82,
                'source_locator' => 'الفرع الأخضر - G016 - الإحداثي 784,497',
                'notes' => 'سهل وجد آل واضحان، ولقب سميط يحتاج تأكيدًا من الصورة الكاملة.',
            ],
            [
                'source_key' => 'green-g017-1592-495',
                'provisional_name' => 'أحمد',
                'normalized_name' => 'أحمد',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G017 - الإحداثي 1592,495',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g018-1110-501',
                'provisional_name' => 'عنوان فرع غير محسوم (G018)',
                'normalized_name' => null,
                'node_type' => 'branch_label',
                'reading_status' => 'unclear',
                'confidence' => 38,
                'source_locator' => 'الفرع الأخضر - G018 - الإحداثي 1110,501',
                'notes' => 'العبارة متعددة الأسطر ولا يمكن اعتماد حروفها من القصاصة الحالية.',
            ],
            [
                'source_key' => 'green-g019-1272-515',
                'provisional_name' => 'علي',
                'normalized_name' => 'علي',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G019 - الإحداثي 1272,515',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g020-1183-520',
                'provisional_name' => 'عبد الرحمن زقوم',
                'normalized_name' => null,
                'node_type' => 'person',
                'reading_status' => 'review',
                'confidence' => 72,
                'source_locator' => 'الفرع الأخضر - G020 - الإحداثي 1183,520',
                'notes' => 'عبد الرحمن واضح، وضبط اللقب زقوم قراءة مرجحة فقط.',
            ],
            [
                'source_key' => 'green-g021-987-541',
                'provisional_name' => 'علوي بن عيسى',
                'normalized_name' => 'علوي بن عيسى',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 95,
                'source_locator' => 'الفرع الأخضر - G021 - الإحداثي 987,541',
                'notes' => 'الاسم مقروء بوضوح جيد.',
            ],
            [
                'source_key' => 'green-g022-1451-539',
                'provisional_name' => 'حسن',
                'normalized_name' => 'حسن',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G022 - الإحداثي 1451,539',
                'notes' => null,
            ],
            [
                'source_key' => 'green-g023-911-546',
                'provisional_name' => 'محمد جد آل مقبل',
                'normalized_name' => null,
                'node_type' => 'branch_label',
                'reading_status' => 'review',
                'confidence' => 86,
                'source_locator' => 'الفرع الأخضر - G023 - الإحداثي 911,546',
                'notes' => 'محمد وجد آل واضحان، ولقب مقبل يحتاج مراجعة أخيرة.',
            ],
            [
                'source_key' => 'green-g024-1376-585',
                'provisional_name' => 'محمد',
                'normalized_name' => 'محمد',
                'node_type' => 'person',
                'reading_status' => 'readable',
                'confidence' => 99,
                'source_locator' => 'الفرع الأخضر - G024 - الإحداثي 1376,585',
                'notes' => null,
            ],
        ];

        foreach ($readings as $reading) {
            ChartReading::updateOrCreate(
                ['source_key' => $reading['source_key']],
                [
                    'provisional_name' => $reading['provisional_name'],
                    'normalized_name' => $reading['normalized_name'],
                    'parent_source_key' => null,
                    'chart_branch' => 'ali_alawi_faqih',
                    'chart_color' => '#8EDB79',
                    'node_type' => $reading['node_type'],
                    'reading_status' => $reading['reading_status'],
                    'confidence' => $reading['confidence'],
                    'source_locator' => $reading['source_locator'],
                    'notes' => $reading['notes'],
                    'is_promoted' => false,
                    'person_id' => null,
                ]
            );
        }
    }

    public function down(): void
    {
        ChartReading::whereIn('source_key', [
            'green-g001-1196-212',
            'green-g002-1560-215',
            'green-g003-969-254',
            'green-g004-741-317',
            'green-g005-1497-374',
            'green-g006-1149-364',
            'green-g007-1363-398',
            'green-g008-1713-385',
            'green-g009-1639-395',
            'green-g010-1226-414',
            'green-g011-1021-436',
            'green-g012-934-434',
            'green-g013-1470-443',
            'green-g014-1318-453',
            'green-g015-541-436',
            'green-g016-784-497',
            'green-g017-1592-495',
            'green-g018-1110-501',
            'green-g019-1272-515',
            'green-g020-1183-520',
            'green-g021-987-541',
            'green-g022-1451-539',
            'green-g023-911-546',
            'green-g024-1376-585',
        ])->delete();
    }
};
